version: '3'

services:
  app:
    container_name: gitlab_app
    image : gitlab/gitlab-ce:13.10.2-ce.0
    ports:
      - 22:22
      - 80:80
      - 443:443
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
      - ./omnibus_config.rb:/omnibus_config.rb
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    secrets:
      - gitlab_root_password
  runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:alpine

secrets:
  gitlab_root_password:
    file: ./root_password.txt